name: create release tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate tag
        run: |
          export TAG_NAME=$(sed -n 6P pubspec.yaml | sed 's/version: //')
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Generate release note
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
 

#          datetime=$(date +'%Y.%m.%d %H:%M:%S')
